version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: task-management-postgres
    environment:
      - POSTGRES_DB=taskmanagement
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "55432:55432"
    networks:
      - task-management-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: taskmanagement-redis
    ports:
      - "6379:6379"
    networks:
      - task-management-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: taskmanagement-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - task-management-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: taskmanagement-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    networks:
      - task-management-network

  app:
    build: .
    container_name: taskmanagement-app
    depends_on:
      - postgres
      - redis
      - kafka
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      DATABASE_URL: "jdbc:postgresql://postgres:55432/taskmanagement"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "1234"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    networks:
      - task-management-network

volumes:
  postgres-data:

networks:
  task-management-network:
    driver: bridge
