spring:
  application:
    name: task-management-system
  
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    org.taskmanagement: DEBUG
    org.springframework.kafka: INFO